/* eslint-disable import/no-anonymous-default-export */
export default {
  GET_USER_GROUPS: 'GET_USER_GROUPS',
  GET_GROUP_ANNOUNCEMENTS: 'GET_GROUP_ANNOUNCEMENTS',
  PATCH_ANNOUNCEMENT: 'PATCH_ANNOUNCEMENT',
  DELETE_ANNOUNCEMENT: 'DELETE_ANNOUNCEMENT',
};
