/* eslint-disable import/no-anonymous-default-export */
export default {
  GET_ASSIGNMENTS: 'GET_ASSIGNMENTS',
  POST_ASSIGNMENT: 'POST_ASSIGNMENT',
  PATCH_ASSIGNMENT: 'PATCH_ASSIGNMENT',
  DELETE_ASSIGNMENT: 'DELETE_ASSIGNMENT',
};
