version: 0.2

phases:
  pre_build:
    commands:
      - cd ctrl
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ctrl/build
